# Generated by Django 4.2 on 2025-10-19 03:39

from django.db import migrations, models
import django.utils.timezone


def create_customers_from_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Customer = apps.get_model('accounts', 'Customer')

    for user in User.objects.all():
        defaults = {
            'email': user.email or f'{user.username}@example.com',
            'password': user.password,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'is_active': user.is_active,
            'date_joined': user.date_joined,
        }

        phone_number = getattr(user, 'phone_number', '')
        address = getattr(user, 'address', '')
        defaults['phone_number'] = phone_number
        defaults['address'] = address

        Customer.objects.update_or_create(
            username=user.username,
            defaults=defaults,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-date_joined"],
            },
        ),
        migrations.RunPython(create_customers_from_users, migrations.RunPython.noop),
    ]
