# Generated by Django 4.2 on 2025-10-19 03:40

from django.db import migrations, models
import django.db.models.deletion


def migrate_order_customers(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Customer = apps.get_model('accounts', 'Customer')
    User = apps.get_model('accounts', 'User')

    for order in Order.objects.all():
        if getattr(order, 'customer_id', None):
            continue

        user_id = getattr(order, 'user_id', None)
        if not user_id:
            continue

        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            continue

        customer = Customer.objects.filter(username=user.username).first()
        if customer is None:
            customer = Customer.objects.create(
                username=user.username,
                email=user.email or f'{user.username}@example.com',
                password=user.password,
                first_name=user.first_name,
                last_name=user.last_name,
                phone_number=getattr(user, 'phone_number', ''),
                address=getattr(user, 'address', ''),
                is_active=user.is_active,
                date_joined=user.date_joined,
            )

        order.customer = customer
        order.save(update_fields=['customer'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customer"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.customer",
            ),
        ),
        migrations.RunPython(migrate_order_customers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.customer",
            ),
        ),
    ]
